# Generated by Django 5.2.17 on 2026-09-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Guest full name', max_length=150)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=50)),
                ('preferred_time', models.CharField(blank=True, default='', help_text="Preferred time window for callback (e.g. 'Morning', 'After 18:00')", max_length=100)),
                ('message', models.TextField(blank=True, default='', help_text='Optional remarks or inquiry submitted by guest')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('CLOSED', 'Closed')], default='NEW', help_text='Internal workflow processing state', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='', help_text='Internal staff remarks (never exposed to public)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Callback Request',
                'verbose_name_plural': 'Callback Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Guest full name', max_length=150)),
                ('email', models.EmailField(help_text='Guest contact email address', max_length=254)),
                ('phone', models.CharField(blank=True, default='', help_text='Optional contact phone number', max_length=50)),
                ('subject', models.CharField(help_text='Subject of message', max_length=200)),
                ('message', models.TextField(help_text='Message body submitted by guest')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('CLOSED', 'Closed')], default='NEW', help_text='Internal workflow processing state', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='', help_text='Internal staff remarks (never exposed to public)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
