# Generated by Django 5.2.17 on 2026-09-23 18:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(help_text='Guest arrival date')),
                ('check_out', models.DateField(help_text='Guest departure date')),
                ('adults', models.PositiveSmallIntegerField(default=1, help_text='Number of adult guests (minimum 1)', validators=[django.core.validators.MinValueValidator(1)])),
                ('children', models.PositiveSmallIntegerField(default=0, help_text='Number of child guests', validators=[django.core.validators.MinValueValidator(0)])),
                ('full_name', models.CharField(help_text='Guest full name', max_length=150)),
                ('phone', models.CharField(help_text='Guest contact phone number', max_length=50)),
                ('email', models.EmailField(help_text='Guest email address', max_length=254)),
                ('special_request', models.TextField(blank=True, default='', help_text='Optional preferences or remarks submitted by guest')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='NEW', help_text='Internal workflow processing state', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='', help_text='Internal staff remarks (never exposed to public)')),
                ('room_name_snapshot', models.CharField(blank=True, default='', help_text='Historical record of room name at time of booking submission', max_length=150)),
                ('price_per_night_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='Historical record of nightly rate at time of booking submission', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(help_text='Requested room category', on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Booking Request',
                'verbose_name_plural': 'Booking Requests',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('adults__gte', 1)), name='booking_adults_gte_1'), models.CheckConstraint(condition=models.Q(('children__gte', 0)), name='booking_children_gte_0'), models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='booking_check_out_gt_check_in')],
            },
        ),
    ]
