# Generated by Django 5.2.17 on 2026-09-23 18:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable amenity name', max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, default='', help_text="Optional icon identifier for frontend icon mapping (e.g., 'wifi', 'tv')", max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order in lists', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this amenity is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['sort_order', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='amenity_sort_order_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Room category title (e.g., 'Deluxe Double')", max_length=150)),
                ('slug', models.SlugField(help_text='URL-safe unique identifier', max_length=160, unique=True)),
                ('short_description', models.CharField(help_text='Concise room overview', max_length=300)),
                ('description', models.TextField(help_text='Full detailed room description')),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Nightly price in local currency (UZS)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_adults', models.PositiveIntegerField(default=1, help_text='Maximum adult capacity (at least 1)', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_children', models.PositiveIntegerField(default=0, help_text='Maximum child capacity', validators=[django.core.validators.MinValueValidator(0)])),
                ('bed_type', models.CharField(help_text="Bed arrangement description (e.g., '1 King Bed')", max_length=100)),
                ('room_size', models.DecimalField(blank=True, decimal_places=2, help_text='Room area in square meters (m²)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this room on homepage/highlights')),
                ('is_active', models.BooleanField(default=True, help_text='Controls public visibility on the website')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order in catalogue', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, help_text='Amenities available in this room type', related_name='rooms', to='rooms.amenity')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/')),
                ('alt_text', models.CharField(blank=True, default='', help_text='Accessible image description', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as the main display image for this room')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Gallery order', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Room Image',
                'verbose_name_plural': 'Room Images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_night__gte', 0)), name='room_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('max_adults__gte', 1)), name='room_max_adults_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('max_children__gte', 0)), name='room_max_children_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='room_sort_order_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('room_size__isnull', True), ('room_size__gt', 0), _connector='OR'), name='room_size_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='roomimage',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='room_image_sort_order_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='roomimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('room',), name='unique_primary_image_per_room'),
        ),
    ]
