# Generated by Django 5.2.17 on 2026-09-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='name_en',
            field=models.CharField(blank=True, default='', help_text='Amenity name in English', max_length=100),
        ),
        migrations.AddField(
            model_name='amenity',
            name='name_ru',
            field=models.CharField(blank=True, default='', help_text='Amenity name in Russian', max_length=100),
        ),
        migrations.AddField(
            model_name='amenity',
            name='name_uz',
            field=models.CharField(blank=True, default='', help_text='Amenity name in Uzbek', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='bed_type_en',
            field=models.CharField(blank=True, default='', help_text='Bed arrangement in English', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='bed_type_ru',
            field=models.CharField(blank=True, default='', help_text='Bed arrangement in Russian', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='bed_type_uz',
            field=models.CharField(blank=True, default='', help_text='Bed arrangement in Uzbek', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='description_en',
            field=models.TextField(blank=True, default='', help_text='Full detailed room description in English'),
        ),
        migrations.AddField(
            model_name='room',
            name='description_ru',
            field=models.TextField(blank=True, default='', help_text='Full detailed room description in Russian'),
        ),
        migrations.AddField(
            model_name='room',
            name='description_uz',
            field=models.TextField(blank=True, default='', help_text='Full detailed room description in Uzbek'),
        ),
        migrations.AddField(
            model_name='room',
            name='name_en',
            field=models.CharField(blank=True, default='', help_text='Room category title in English', max_length=150),
        ),
        migrations.AddField(
            model_name='room',
            name='name_ru',
            field=models.CharField(blank=True, default='', help_text='Room category title in Russian', max_length=150),
        ),
        migrations.AddField(
            model_name='room',
            name='name_uz',
            field=models.CharField(blank=True, default='', help_text='Room category title in Uzbek', max_length=150),
        ),
        migrations.AddField(
            model_name='room',
            name='short_description_en',
            field=models.CharField(blank=True, default='', help_text='Concise room overview in English', max_length=300),
        ),
        migrations.AddField(
            model_name='room',
            name='short_description_ru',
            field=models.CharField(blank=True, default='', help_text='Concise room overview in Russian', max_length=300),
        ),
        migrations.AddField(
            model_name='room',
            name='short_description_uz',
            field=models.CharField(blank=True, default='', help_text='Concise room overview in Uzbek', max_length=300),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(help_text='Human-readable amenity name (fallback)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_type',
            field=models.CharField(help_text='Bed arrangement description (fallback)', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(help_text='Full detailed room description (fallback)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='Room category title (fallback)', max_length=150),
        ),
        migrations.AlterField(
            model_name='room',
            name='short_description',
            field=models.CharField(help_text='Concise room overview (fallback)', max_length=300),
        ),
    ]
