# Generated by Django 5.2.17 on 2026-09-23 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload gallery image', upload_to='gallery/')),
                ('title', models.CharField(blank=True, default='', help_text='Optional image title', max_length=150)),
                ('alt_text', models.CharField(blank=True, default='', help_text='Accessible image description', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order in gallery', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this image appears in the gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='gallery_image_sort_order_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='HotelInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Coco Hotel', help_text='Hotel name', max_length=150)),
                ('hero_title', models.CharField(default='Welcome to Coco Hotel', help_text='Homepage hero section main title', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default='', help_text='Homepage hero section supporting description')),
                ('about_title', models.CharField(default='About Coco Hotel', help_text='About section heading', max_length=200)),
                ('about_text', models.TextField(help_text='Detailed overview and story of the hotel')),
                ('phone', models.CharField(help_text='Primary contact phone number', max_length=50)),
                ('secondary_phone', models.CharField(blank=True, default='', help_text='Alternative contact phone number', max_length=50)),
                ('email', models.EmailField(help_text='Official contact email address', max_length=254)),
                ('address', models.CharField(help_text='Physical hotel address', max_length=255)),
                ('map_url', models.URLField(blank=True, default='', help_text='External link to Google Maps / Yandex Maps location')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Geographic latitude coordinate (-90 to 90)', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Geographic longitude coordinate (-180 to 180)', max_digits=9, null=True)),
                ('check_in_time', models.TimeField(blank=True, help_text='Standard daily check-in time', null=True)),
                ('check_out_time', models.TimeField(blank=True, help_text='Standard daily check-out time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel Information',
                'verbose_name_plural': 'Hotel Information',
                'constraints': [models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='hotel_info_latitude_valid'), models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='hotel_info_longitude_valid')],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Offer headline', max_length=150)),
                ('slug', models.SlugField(help_text='URL-safe unique identifier', max_length=160, unique=True)),
                ('short_description', models.CharField(help_text='Concise summary for promotion cards', max_length=300)),
                ('description', models.TextField(help_text='Full promotional details and terms')),
                ('image', models.ImageField(blank=True, help_text='Promotional banner image', null=True, upload_to='promotions/')),
                ('valid_from', models.DateField(blank=True, help_text='Start date of promotion (optional)', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='End date of promotion (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Master toggle for promotion availability')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='promotion_sort_order_gte_0'), models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='promotion_valid_until_gte_valid_from')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service title', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Concise service description')),
                ('icon', models.CharField(blank=True, default='', help_text='Icon identifier for frontend icon mapping', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is active and offered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['sort_order', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='service_sort_order_gte_0')],
            },
        ),
    ]
