# Generated by Django 5.2.17 on 2026-09-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_seed_initial_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='alt_text_en',
            field=models.CharField(blank=True, default='', help_text='Accessible image description in English', max_length=200),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='alt_text_ru',
            field=models.CharField(blank=True, default='', help_text='Accessible image description in Russian', max_length=200),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='alt_text_uz',
            field=models.CharField(blank=True, default='', help_text='Accessible image description in Uzbek', max_length=200),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_en',
            field=models.CharField(blank=True, default='', help_text='Optional image title in English', max_length=150),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_ru',
            field=models.CharField(blank=True, default='', help_text='Optional image title in Russian', max_length=150),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_uz',
            field=models.CharField(blank=True, default='', help_text='Optional image title in Uzbek', max_length=150),
        ),
        migrations.AddField(
            model_name='hotelinformation',
            name='about_text_en',
            field=models.TextField(blank=True, default='', help_text='Detailed overview and story in English'),
        ),
        migrations.AddField(
            model_name='hotelinformation',
            name='about_text_ru',
            field=models.TextField(blank=True, default='', help_text='Detailed overview and story in Russian'),
        ),
        migrations.AddField(
            model_name='hotelinformation',
            name='about_text_uz',
            field=models.TextField(blank=True, default='', help_text='Detailed overview and story in Uzbek'),
        ),
        migrations.AddField(
            model_name='hotelinformation',
            name='about_title_en',
            field=models.CharField(blank=True, default='', help_text='About section heading in English', max_length=200),
        ),
        migrations.AddField(
            model_name='hotelinformation',
            name='about_title_ru',
            field=models.CharField(blank=True, default='', help_text='About section heading in Russian', max_length=200),
        ),
        migrations.AddField(
            model_name='hotelinformation',
            name='about_title_uz',
            field=models.CharField(blank=True, default='', help_text='About section heading in Uzbek', max_length=200),
        ),
        migrations.AddField(
            model_name='hotelinformation',
            name='address_en',
            field=models.CharField(blank=True, default='', help_text='Physical hotel address in English', max_length=255),
        ),
        migrations.AddField(
            model_name='hotelinformation',
            name='address_ru',
            field=models.CharField(blank=True, default='', help_text='Physical hotel address in Russian', max_length=255),
        ),
        migrations.AddField(
            model_name='hotelinformation',
            name='address_uz',
            field=models.CharField(blank=True, default='', help_text='Physical hotel address in Uzbek', max_length=255),
        ),
        migrations.AddField(
            model_name='hotelinformation',
            name='hero_subtitle_en',
            field=models.TextField(blank=True, default='', help_text='Hero subtitle in English'),
        ),
        migrations.AddField(
            model_name='hotelinformation',
            name='hero_subtitle_ru',
            field=models.TextField(blank=True, default='', help_text='Hero subtitle in Russian'),
        ),
        migrations.AddField(
            model_name='hotelinformation',
            name='hero_subtitle_uz',
            field=models.TextField(blank=True, default='', help_text='Hero subtitle in Uzbek'),
        ),
        migrations.AddField(
            model_name='hotelinformation',
            name='hero_title_en',
            field=models.CharField(blank=True, default='', help_text='Hero title in English', max_length=200),
        ),
        migrations.AddField(
            model_name='hotelinformation',
            name='hero_title_ru',
            field=models.CharField(blank=True, default='', help_text='Hero title in Russian', max_length=200),
        ),
        migrations.AddField(
            model_name='hotelinformation',
            name='hero_title_uz',
            field=models.CharField(blank=True, default='', help_text='Hero title in Uzbek', max_length=200),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description_en',
            field=models.TextField(blank=True, default='', help_text='Full promotional details and terms in English'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description_ru',
            field=models.TextField(blank=True, default='', help_text='Full promotional details and terms in Russian'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description_uz',
            field=models.TextField(blank=True, default='', help_text='Full promotional details and terms in Uzbek'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='short_description_en',
            field=models.CharField(blank=True, default='', help_text='Summary in English', max_length=300),
        ),
        migrations.AddField(
            model_name='promotion',
            name='short_description_ru',
            field=models.CharField(blank=True, default='', help_text='Summary in Russian', max_length=300),
        ),
        migrations.AddField(
            model_name='promotion',
            name='short_description_uz',
            field=models.CharField(blank=True, default='', help_text='Summary in Uzbek', max_length=300),
        ),
        migrations.AddField(
            model_name='promotion',
            name='title_en',
            field=models.CharField(blank=True, default='', help_text='Offer headline in English', max_length=150),
        ),
        migrations.AddField(
            model_name='promotion',
            name='title_ru',
            field=models.CharField(blank=True, default='', help_text='Offer headline in Russian', max_length=150),
        ),
        migrations.AddField(
            model_name='promotion',
            name='title_uz',
            field=models.CharField(blank=True, default='', help_text='Offer headline in Uzbek', max_length=150),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, default='', help_text='Service description in English'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(blank=True, default='', help_text='Service description in Russian'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_uz',
            field=models.TextField(blank=True, default='', help_text='Service description in Uzbek'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(blank=True, default='', help_text='Service title in English', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(blank=True, default='', help_text='Service title in Russian', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='name_uz',
            field=models.CharField(blank=True, default='', help_text='Service title in Uzbek', max_length=100),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_text',
            field=models.CharField(blank=True, default='', help_text='Accessible image description (fallback)', max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Optional image title (fallback)', max_length=150),
        ),
        migrations.AlterField(
            model_name='hotelinformation',
            name='about_text',
            field=models.TextField(help_text='Detailed overview and story of the hotel (fallback)'),
        ),
        migrations.AlterField(
            model_name='hotelinformation',
            name='about_title',
            field=models.CharField(default='About Coco Hotel', help_text='About section heading (fallback)', max_length=200),
        ),
        migrations.AlterField(
            model_name='hotelinformation',
            name='address',
            field=models.CharField(help_text='Physical hotel address (fallback)', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelinformation',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='', help_text='Homepage hero section supporting description (fallback)'),
        ),
        migrations.AlterField(
            model_name='hotelinformation',
            name='hero_title',
            field=models.CharField(default='Welcome to Coco Hotel', help_text='Homepage hero section main title (fallback)', max_length=200),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(help_text='Full promotional details and terms (fallback)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='short_description',
            field=models.CharField(help_text='Concise summary for promotion cards (fallback)', max_length=300),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(help_text='Offer headline (fallback)', max_length=150),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Concise service description (fallback)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Service title (fallback)', max_length=100, unique=True),
        ),
    ]
