# Generated by Django 5.2.17 on 2026-09-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_backfill_multilingual_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('rooms', 'Rooms'), ('interior', 'Interior'), ('dining', 'Dining'), ('exterior', 'Exterior')], default='interior', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelinformation',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Hotel story photo', upload_to='hotel/'),
        ),
        migrations.AddField(
            model_name='hotelinformation',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Homepage cover photo', upload_to='hotel/'),
        ),
    ]
